### ISSUE TITLE
Php error when clicking the pay with yenepay button

### ISSUE THREAD

**Issue by abdu4188** [YenePay/yenepay.sample_shop.php#1]
I hosted the whole repo with xampps local apache server and when I click the pay with yenepay button I get the following error.

Warning: require_once(/opt/lampp/htdocs/yenepay-shop/vendor/yenepay/php-sdk/src/CheckoutHelper.php): failed to open stream: No such file or directory in /opt/lampp/htdocs/yenepay-shop/process.php on line 7

Fatal error: require_once(): Failed opening required '/opt/lampp/htdocs/yenepay-shop/vendor/yenepay/php-sdk/src/CheckoutHelper.php' (include_path='.:/opt/lampp/lib/php') in /opt/lampp/htdocs/yenepay-shop/process.php on line 7
And when I check the directory vendor/yenepay/php-sdk there are no files in there.
Thanks

**Comment by tinspu** [comment]
i think you forgot to install the php-sdk dependency (i.e.https://github.com/YenePay/yenepay.sdk.php )

**Comment by abdu4188** [comment]
Okay that worked. I thought the php sdk source would exist in the repo it self.
Thank you.
