### ISSUE TITLE
Contribution blocked

### ISSUE THREAD

**Issue by agebeyaw** [YenePay/yenepay.sample_shop.php#2]
While trying to test the sample shop, I end up doing the following.

- an overall cleaning up and formatting of the code for indentation
- used an `.env` file for easier configuration
- created reusable blocks 
- ignored IDE files and vendor
- updated the readme with all steps for setting up the sample shop

If you give access, I can create a PR with my modifications.

PS: well done team YenePay!

**Comment by tinspu** [comment]
if you want to merge your changes, please create a pull request.
Thank you for the contribution and appreciation.

**Comment by agebeyaw** [comment]
Am not able to create a PR, I do not have access to create a branch. 

Check if there are any branch protection rules. You can invite me as a contributor, if you want. https://github.com/YenePay/yenepay.sample_shop.php/settings/access

**Comment by tinspu** [comment]
please fork the repo to your account .... make the changes you want ..., then create a pull request if you want your changes to be applied (i.e. https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by agebeyaw** [comment]
Selam @tinspu ,

done! https://github.com/YenePay/yenepay.sample_shop.php/pull/3/
